name: Copy App to EC2

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  copy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy App to EC2
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./ ubuntu@34.201.92.1 :/home/ubuntu/
          

